### ISSUE TITLE
NPE in /admin/blacklist

### ISSUE THREAD

**Issue by ScalaWilliam** [ActionFPS/ActionFPS#481]
```
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: [error] o.s.w.s.a.HttpWebHandlerAdapter - [526d49dc] 500 Server Error for HTTP GET "/admin/blacklist"
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: java.lang.NullPointerException: null
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at com.actionfps.admin.ActionFPSAdminRouter.lambda$createRouter$32(ActionFPSAdminRouter.java:348)
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at com.actionfps.admin.ActionFPSAdminRouter.lambda$createRouter$34(ActionFPSAdminRouter.java:350)
Apr 02 10:42:31 odin.duel.gg actionfps-web[25302]: at org.springframework.web.reactive.function.server.RouterFunctions.lambda$null$3(RouterFunctions.java:261)
```

**Comment by ScalaWilliam** [comment]
Edited data directly
